[package]
name = "geoq"
version = "0.1.0"
authors = ["Horace Williams <horace.d.williams@gmail.com>"]

[dependencies]
clap = "2.31.2"
regex = "1.0.0"
lazy_static = "1.0.1"
geo = "0.9.1"
geohash = "0.7.0"
wkt = "0.0.6"
geojson = "0.11.0"

[dev-dependencies]
assert_cli = "0.6"